---
title: "Australia Next Day Rain Prediction"
author: "Allister Mounsey"
date: "11 February 2019"
output: bookdown::pdf_document2
---

```{r setup, include=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width=7,fig.height=6)
suppressMessages(library(tidyverse))
suppressMessages(library(ggalt))
suppressMessages(library(caret))
suppressMessages(library(png))
suppressMessages(library(summarytools))
suppressMessages(library(factoextra))

load('rda/datasets.rda')
gc() 
```

#Introduction

#Methods and Analysis
Figure \@ref(fig:map) shows

```{r map,echo=FALSE,warning=FALSE,fig.cap="\\label{Figure:map}Rain Days across Australia \\ Source: <http://www.bom.gov.au/jsp/ncc/climate_averages/raindays/index.jsp>" }
aussie_map<-readPNG('figs/rain1mman.png')
grid::grid.raster(aussie_map)
```

Figure \@ref(fig:seasonal) shows seasonal 

```{r seasonal,echo=FALSE,warning=FALSE,fig.cap="\\label{Figure:seaonal}Monthly Rainfall Patterns by Location"}
trainSet_dv%>%group_by(Location,Month)%>%
  summarise(Daily_rainfall=mean(Rainfall),Number_rain_days=30.5*mean(ifelse(RainToday=='No',0,1)))%>%
  select(Location,Month,Daily_rainfall,Number_rain_days)%>%filter(Location=='Darwin'|Location=='Portland')%>%
  ggplot(aes(x=Month,y=Number_rain_days,size=Daily_rainfall))+geom_point()+facet_wrap(~Location)+
  labs(y='Mean Number of Rain Days',size='Mean Daily Rainfall in mm')+
  theme_bw()+theme(axis.text.x = element_text(angle=90),legend.position = 'bottom')
```

Separation. Figure \@ref(fig:wellsep) example

```{r wellsep,echo=FALSE,warning=FALSE,fig.cap="\\label{Figure:wellsep}Examples of Some Well Separated Cases"}
g1<-trainSet_dv%>%ggplot(aes(ifelse(RainTomorrow==0,'No','Yes'),Humidity3pm))+geom_boxplot()+
  labs(x='RainTomorrow')+theme_bw()

g2<-trainSet_dv%>%ggplot(aes(ifelse(RainTomorrow==0,'No','Yes'),Cloud3pm))+geom_boxplot()+
  labs(x='RainTomorrow')+theme_bw()
gridExtra::grid.arrange(g1,g2, nrow=1)
```

Not well separated Figure \@ref(fig:notwellsep)

```{r notwellsep,echo=FALSE,warning=FALSE,fig.cap="\\label{Figure:notwellsep}Examples of Some **NOT** Well Separated Cases"}
g1<-trainSet_dv%>%ggplot(aes(ifelse(RainTomorrow==0,'No','Yes'),WindSpeed9am))+geom_boxplot()+
  labs(x='RainTomorrow')+theme_bw()

g2<-trainSet_dv%>%ggplot(aes(ifelse(RainTomorrow==0,'No','Yes'),Temp9am))+geom_boxplot()+
  labs(x='RainTomorrow')+theme_bw()
gridExtra::grid.arrange(g1,g2, nrow=1)
```


```{r sepNumvar,echo=FALSE,warning=FALSE}
x<-matrix(unlist(sapply(numVars,ksWrapper),use.names = F),ncol=3,byrow=T)
x<-as.data.frame(x)[,-3]
names(x)<-c('NumericVariable','D')
x$D<-round(as.numeric(as.character(x$D)),digits = 2)

kableExtra::kable_styling(knitr::kable(x,booktabs = TRUE,
  caption = 'Results of Kolmogorov-Smirnov test on Conditional Distributions (RainTomorrow = 0 vs. RainTomorrow = 0)',
  row.names = NA,col.names = NA),latex_options = "hold_position")
```


```{r locMon,echo=FALSE,warning=FALSE,fig.cap="\\label{Figure:locMon}Finding Optimal Number for Location - Month Clustering"}
g1<-fviz_nbclust(check,FUN=hcut,method = 'wss')
g2<-fviz_nbclust(check,FUN=hcut,method = 'silhouette')
g3<-fviz_gap_stat(gap_stat)
gridExtra::grid.arrange(g1,g2,g3, ncol=1)
```


```{r locMon1,echo=FALSE,warning=FALSE}
clustmat<-trainSet_dv%>%group_by(Location,Month)%>%
  summarise(rainDays=30.5*mean(RainTomorrow),sd_rainDays=sd(RainTomorrow))%>%
  mutate(label=paste(Location,Month, sep = '_'))%>%ungroup()%>%
  select(Location,Month)%>%mutate(cluster=clust)

kableExtra::kable_styling(knitr::kable(clustmat%>%spread(key=Month,value=cluster),booktabs = TRUE,
  caption = 'Location-Month Clusters',
  row.names = NA,col.names = NA),latex_options = "hold_position")
```

```{r locMon2,echo=FALSE,warning=FALSE,fig.cap="\\label{Figure:locMon2}Number of Rain Days and Variability in Rain Days accross Clusters"}
fviz_cluster(list(data=check,cluster=clust), geom = 'point',
             xlab = 'Rain Days (Standardized)',ylab = 'Variability in Rain Days (Standardized)',
             main = NULL,ggtheme = theme_bw())
```

```{r winddir,echo=FALSE,warning=FALSE,message=FALSE}
x1<-ifelse(trainSet_dv[trainSet_dv$Location=="Cobar",]$RainTomorrow==0,'No','Yes')
x2<- trainSet_dv[trainSet_dv$Location=="Cobar",]$WindGustDir
x<-ctable(x1,x2, prop = 'c')[2] # the Crosstab as proportions the 2nd table in the list 
kableExtra::kable_styling(knitr::kable(x,digits = 2,booktabs = TRUE,
  caption = 'Conditional Probabilities No Rain Tomorrow vs. Rain Tomorrow Given WindGust Direction (Location = Cobar) ',
  row.names = NA,col.names = NA),latex_options = "hold_position", full_width = T)
  
```

```{r raindir1, echo=FALSE,warning=FALSE,message=FALSE }
x1<-as.data.frame(ctable(trainSet_dv$rainDirGust,trainSet_dv$RainTomorrow,omit.headings = F)[2],
                  row.names = c('rainDirGust=0','rainDirGust=1','Total'))
names(x1)<-c('RainTomorrow=0','RainTomorrow=1','Total')
x2<-as.data.frame(ctable(trainSet_dv$rainDir9am,trainSet_dv$RainTomorrow,omit.headings = F)[2],
                  row.names = c('rainDir9am=0','rainDir9am=1','Total'))
names(x2)<-c('RainTomorrow=0','RainTomorrow=1','Total')
x3<-as.data.frame(ctable(trainSet_dv$rainDir3pm,trainSet_dv$RainTomorrow,omit.headings = F)[2],
                  row.names = c('rainDir3pm=0','rainDir3pm=1','Total'))
names(x3)<-c('RainTomorrow=0','RainTomorrow=1','Total')

knitr::kable(x1,digits = 2,booktabs=T, caption = "Probabilites of Rain Tomorrow Conditioned on rainDir9am")

```

```{r raindir2, echo=FALSE,warning=FALSE,message=FALSE }
knitr::kable(x2,digits = 2,booktabs=T,caption = "Probabilites of Rain Tomorrow Conditioned on rainDir3pm")

```

```{r raindir3, echo=FALSE,warning=FALSE,message=FALSE }
knitr::kable(x3,digits = 2,booktabs=T,caption = "Probabilites of Rain Tomorrow Conditioned on rainDirGust")

```

#Results

#Conclusion 


